sudo: required
services:
  - docker

before_install:
  - docker build -t yanivillouz/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true yanivillouz/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  app: "yanivi-docker"
  env: "YaniviDocker-env"
  bucket_name: "elasticbeanstalk-eu-west-3-345824986691"
  bucket_path: "yanivi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
